server:
  port: 8080
spring:
  profiles:
    active: ${env.spring_profiles_active:local}
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB
  datasource:
    url: jdbc:postgresql://${env.DB_HOST:localhost}:${env.DB_PORT:5432}/${env.spring_profiles_active}_location
    username: ${env.DB_USER:ok}
    password: ${env.DB_PASSWORD:ok}
    hikari:
      idle-timeout: 20000
      minimum-idle: 1
      maximum-pool-size: 8
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
#        metadata_builder_contributor: com.briolink.locationservice.jpa.Functions
    generate-ddl: false
    show-sql: false
    open-in-view: false
  liquibase:
    change-log: migration/db.changelog.yml
app:
  csv-files-location:
    country: https://raw.githubusercontent.com/dr5hn/countries-states-cities-database/master/csv/countries.csv
    state: https://raw.githubusercontent.com/dr5hn/countries-states-cities-database/master/csv/states.csv
    city: https://raw.githubusercontent.com/dr5hn/countries-states-cities-database/master/csv/cities.csv
